- title: 社区版
  fulltitle: GridLinks 社区版
  description: GridLinks 文档
  tag: ce
  icon: /images/thingsboard-cm-icon.svg
  path: /docs/
  guides: /docs/guides/
  getStarted: /docs/getting-started-guides/helloworld/
  docsPrefix: /docs/
# - title: 专业版
#   fulltitle: GridLinks 专业版
#   description: GridLinks 文档
#   tag: pe
#   icon: /images/thingsboard-p-icon.svg
#   path: /docs/pe/
#   guides: /docs/pe/guides/
#   getStarted: /docs/pe/getting-started-guides/helloworld/
#   docsPrefix: /docs/pe/
- title: 云服务
  fulltitle: GridLinks 云服务
  description: GridLinks 文档
  tag: paas
  icon: /images/thingsboard-c-icon.svg
  path: /docs/paas/
  guides: /docs/paas/guides/
  getStarted: /docs/paas/getting-started-guides/helloworld/
  docsPrefix: /docs/paas/
- title: 边缘计算
  fulltitle: GridLinks 边缘计算
  description: GridLinks 边缘计算文档
  tag: edge
  icon: /images/thingsboard-e-icon.svg
  path: /docs/edge/
# - title: PE边缘计算
#   fulltitle: GridLinks PE边缘计算
#   description: GridLinks PE边缘计算文档
#   tag: edge-pe
#   icon: /images/thingsboard-e-icon.svg
#   path: /docs/pe/edge/
- title: 物联网网关
  fulltitle: GridLinks物联网网关
  description: GridLinks 文档
  tag: gw
  icon: /images/gateway-icon.svg
  path: /docs/iot-gateway/
  getStarted: /docs/iot-gateway/getting-started/
# - title: 授权服务器
#   fulltitle: GridLinks 授权服务器
#   description: GridLinks 文档
#   tag: license
#   icon: /images/license-icon.svg
#   path: /products/license-server/
- title: 数据分析
  fulltitle: 数据分析
  description: 数据文档
  tag: trendz
  icon: /images/trendz-icon.svg
  path: /docs/trendz/
  getStarted: /docs/trendz/getting-started/
# - title: 移动应用
#   fulltitle: GridLinks 移动应用
#   description: 移动应用文档
#   tag: mobile
#   icon: /images/tb-mobile-icon.svg
#   path: /docs/mobile/
#   docsPrefix: /docs/mobile/
#   getStarted: /docs/mobile/getting-started/
# - title: PE移动应用
#   fulltitle: GridLinks PE移动应用
#   description: PE移动应用文档
#   tag: mobile-pe
#   icon: /images/tb-pe-mobile-icon.svg
#   path: /docs/pe/mobile/
#   docsPrefix: /docs/pe/mobile/
#   getStarted: /docs/pe/mobile/getting-started/
# - title: MQTT代理
#   fulltitle: MQTT代理
#   description: MQTT代理文档
#   tag: mqtt-broker  
#   icon: /images/tbmq-icon.svg
#   path: /docs/mqtt-broker/
#   getStarted: /docs/mqtt-broker/getting-started/